# Generated by Django 5.2 on 2025-04-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lesson_id', models.CharField(max_length=5)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10)),
                ('stu_number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('lesson_list', models.ManyToManyField(to='student.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10)),
                ('tea_number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('lesson_list', models.ManyToManyField(to='student.lesson')),
            ],
        ),
    ]
