# Generated by Django 5.2 on 2025-04-29 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_time', models.CharField(max_length=100)),
                ('exam_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.lesson')),
            ],
        ),
    ]
