# Generated by Django 5.2 on 2025-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='num_q',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
