# Generated by Django 5.2 on 2025-04-29 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_exam_num_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=4)),
                ('text_q', models.TextField()),
                ('q_grade', models.CharField(max_length=20)),
                ('lesson_l', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.lesson')),
            ],
        ),
    ]
