# Generated by Django 5.2 on 2025-04-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ex_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='num_q',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
