# Generated by Django 5.2 on 2025-04-30 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_lesson_ex_time_lesson_num_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lesson_l',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.lesson'),
        ),
    ]
