# Generated by Django 5.2 on 2025-05-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_question_lesson_l'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_an', models.TextField()),
                ('q_number', models.CharField(max_length=20)),
                ('lesson_l_l', models.CharField(max_length=30)),
                ('studnet_number', models.CharField(max_length=8)),
            ],
        ),
    ]
